//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cv.rc
//

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_CV_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_CV			107
#define IDI_SMALL				108
#define IDC_CV			109
#define IDC_WATCHLIST 200
#define IDC_PROMPT_EDIT 201
#define IDD_PROMPT 202
#define RAMMENU_FILE_RECENT 203
#define IDC_EDIT_COMPAREADDRESS 204
#define IDC_1_BYTE 205
#define IDC_2_BYTES 206
#define IDC_4_BYTES 207
#define IDC_SIGNED 208
#define IDC_UNSIGNED 209
#define IDC_HEX 210
#define ID_WATCHES_UPDOWN 211
#define IDC_C_WATCH_UP 212
#define IDC_C_WATCH_DOWN 213
#define RAMMENU_FILE_SAVE 214
#define RAMMENU_FILE_SAVEAS 215
#define RAMMENU_FILE_OPEN 216
#define RAMMENU_FILE_APPEND 217
#define RAMMENU_FILE_AUTOLOAD 218
#define RAMMENU_FILE_SAVEWINDOW 219
#define RAMMENU_FILE_NEW 220
#define IDC_C_WATCH_REMOVE 221
#define IDC_C_WATCH_EDIT 222
#define IDD_EDITWATCH 223
#define IDC_C_WATCH_DUPLICATE 224
#define IDC_C_ADDCHEAT 225
#define IDC_C_WATCH 226
#define ID_RAM_WATCH 227
#define IDD_RAMWATCH 228
#define IDM_RESET 229
#define IDC_EDIT_COMPAREVALUE 230
#define IDC_EDIT_COMPARECHANGES 231
#define IDC_EDIT_DIFFBY 232
#define IDC_EDIT_MODBY 233
#define IDC_RAMLIST 234
#define IDC_C_ELIMINATE 235
#define IDC_C_MISALIGN 236
#define IDC_C_AUTOSEARCH 237
#define IDC_MISALIGN 238
#define IDC_LESSTHAN 239
#define IDC_MORETHAN 240
#define IDC_NOMORETHAN 241
#define IDC_NOLESSTHAN 242
#define IDC_EQUALTO 243
#define IDC_DIFFERENTFROM 244
#define IDC_MODULO 245
#define IDC_PREVIOUSVALUE 246
#define IDC_SPECIFICVALUE 247
#define IDC_SPECIFICADDRESS 248
#define IDC_NUMBEROFCHANGES 249
#define IDC_DIFFERENTBY 250
#define IDC_C_RESET 251
#define IDC_C_RESET_CHANGES 252
#define IDC_C_UNDO 253
#define IDC_C_SEARCH 254
#define ID_RAM_SEARCH 255
#define IDD_RAMSEARCH 256
#define IDC_PROMPT_TEXT 257
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
